# Generated by Django 2.2.7 on 2019-11-30 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20191111_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('one_pager', models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('started', 'Started'), ('done', 'Done')], default='not_started', max_length=20, verbose_name='One Pager')),
                ('met_mgt', models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('started', 'Started'), ('done', 'Done')], default='not_started', max_length=20, verbose_name='Met with Management')),
                ('financial_model', models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('started', 'Started'), ('done', 'Done')], default='not_started', max_length=20)),
                ('risk_matrix', models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('started', 'Started'), ('done', 'Done')], default='not_started', max_length=20)),
                ('presented_ic', models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('started', 'Started'), ('done', 'Done')], default='not_started', max_length=20)),
                ('investment_memo', models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('started', 'Started'), ('done', 'Done')], default='not_started', max_length=20)),
                ('term_sheet', models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('started', 'Started'), ('done', 'Done')], default='not_started', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='IC_Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'IC Member',
                'verbose_name_plural': 'IC Members',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.RemoveField(
            model_name='companynote',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companynote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='company',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='company',
        ),
        migrations.AddField(
            model_name='contact',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.Deal'),
        ),
        migrations.AddField(
            model_name='contact',
            name='first_name',
            field=models.CharField(default='first', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(default='last', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='lead_ic',
            field=models.CharField(blank=True, help_text="IC member that's championing the deal", max_length=100),
        ),
        migrations.AddField(
            model_name='deal',
            name='name',
            field=models.CharField(default='deal', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='reception_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='deal',
            name='rejection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='sector',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contactnote',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='deal',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='deal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dealnote',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='CompanyNote',
        ),
        migrations.AddField(
            model_name='checklist',
            name='deal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='crm.Deal'),
        ),
    ]
